### ISSUE TITLE
remove annoying node dots on branches

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#348]
![Screen Shot 2019-04-04 at 3 10 01 PM](https://user-images.githubusercontent.com/1659198/55582051-79f6d180-56ec-11e9-955e-8d5ed7929ddf.png)
Trees are once again appearing with dots or squares for internal nodes with 1 child.  Users do not expect this and do not know what it means.  Therefore, it is confusing. Please remove it.

**Comment by bomeara** [comment]
Generally, having an option to return a tree without singleton nodes would be great -- it would fix the problem here, as well as for some of @jwiggi18's current work intended for displaying trees on EOL

**Comment by abusalehmdtayeen** [comment]
I have added the singleton node removal feature by default as @bomeara suggested. I think it is fixed now. @arlin can you please test your example again?

**Comment by arlin** [comment]
Thanks!
![Screen Shot 2019-04-06 at 9.17.33 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/555b5266657c0c8300c2bee1/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77276454f56b7191a371f1132c4f5c5c5edd3c4a4356bcbbd671f3e57862804e0ee8d43f5a76c16842f8e9d74eea04ec208b4b87e5b5dc49d2f42f67b6d5db1063474f4dcbed5727a19041c95df34fe44853a3113160ee7f2431.png)

**Comment by arlin** [comment]
I'm seeing this problem again. It seems to depend on the source of the tree.  Here is what to do.  Begin with this list

`
Equus caballus
Cervus canadensis
Sus scrofa
Balaenoptera acutorostrata
Balaena mysticetus
Orcinus orca
Platanista gangetica
Hippopotamus amphibius
Mirounga leonina
Hydrurga leptonyx
Phoca vitulina
Otaria byronia
Elephas maximus
Dugong dugon
Trichechus manatus
Ursus maritimus
Procyon lotor
`

Get the tree.  Get the OT scaled tree.  Add the 3 yellow boxes.  

Now do the same thing, but use the Median scaled tree.   the images below show both of them.
![median_scaled.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/555b5266657c0c8300c2bee1/125516c66e82c728ace21e0d46e5919e2a838d969ceabe4fa159b2d86b56357c2301a03f32dfa17dea1779545d581bff15090a15a9fcdf2ba6b23e23830a0effcd7f1d2598694ef1e1c84afd13b0328a488fb7b98f49c6eb3d25ef8c8e473c0c48.png)
![ot_scaled.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/555b5266657c0c8300c2bee1/125516c66e82c728ace21e0d46e780a5308182a58aedfd0fe64de29b234324676b5ee17e25d0e17ded157e020b0e1bfd145d0944fcfd8b78afe03962964e49bc8f3900299f7744eeaa880dbe06b0218e4a80b0bf8a4cc8ef3c2ce399c2.png)

**Comment by abusalehmdtayeen** [comment]
@ducvan0212, I think the problem is happening because ete preserves the node actions between different calls. Since the tree is changed after scaling, sometimes the boxes remain in their old places. Can you please change the treeid every time scaling method is called. That would reset the actions and probably solve the problem.

**Comment by ducvan0212** [comment]
@abusalehmdtayeen can you check if the issue still exists?

**Comment by abusalehmdtayeen** [comment]
I think the problem is fixed now. We clear the node actions when any scaling method is applied. So the user needs to apply his actions for the new version of the tree.

**Comment by abusalehmdtayeen** [comment]
@arlin , if you are referring to the little misplaced dots, then we can't fix it. It is an internal issue of ETE.

**Comment by arlin** [comment]
is the fix on production yet?  I tried it tonight and I still see the problem.

**Comment by abusalehmdtayeen** [comment]
@arlin , I think I have finally fixed the problem. Can you please check? I want to close this issue as soon as possible.
